// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CashFlowBotTests.Tests.SmallCircle
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Business")]
    [NUnit.Framework.CategoryAttribute("non-parallel")]
    [NUnit.Framework.CategoryAttribute("do-cleanup")]
    public partial class BusinessFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "non-parallel",
                "do-cleanup"};
        
#line 1 "Business.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Tests/SmallCircle", "Business", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("I can buy businesses")]
        public void ICanBuyBusinesses()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("I can buy businesses", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
 testRunner.Given("I am \'Inayah Hodge\' user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
  testRunner.And("I play as \'Car mechanic\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 9
  testRunner.And("I get $200,000 in cash", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Title",
                            "Price",
                            "First Payment",
                            "Monthly Cashflow"});
                table1.AddRow(new string[] {
                            "Car wash",
                            "20,000",
                            "20,000",
                            "800"});
                table1.AddRow(new string[] {
                            "Company",
                            "25,000",
                            "20,000",
                            "1000"});
                table1.AddRow(new string[] {
                            "Enterprise",
                            "30,000",
                            "25,000",
                            "1500"});
                table1.AddRow(new string[] {
                            "Limited partnership",
                            "100,000",
                            "30,000",
                            "1600"});
                table1.AddRow(new string[] {
                            "Passage",
                            "150,000",
                            "40,000",
                            "1,800"});
                table1.AddRow(new string[] {
                            "Pizzeria",
                            "500,000",
                            "50,000",
                            "2500"});
#line 10
 testRunner.When("I buy businesses:", ((string)(null)), table1, "When ");
#line hidden
#line 18
 testRunner.Then("My Data is following:", @"*Profession:* Car mechanic
*Cash:* $16,390
*Salary:* $2,000
*Income:* $9,200
*Expenses:* $1,280
*Cashflow:* $9,920

*Assets:*
• *Car Wash* - Price: $20,000, Cashflow: $800
• *Company* - Price: $25,000, Mortgage: $5,000, Cashflow: $1,000
• *Enterprise* - Price: $30,000, Mortgage: $5,000, Cashflow: $1,500
• *Limited Partnership* - Price: $100,000, Mortgage: $70,000, Cashflow: $1,600
• *Passage* - Price: $150,000, Mortgage: $110,000, Cashflow: $1,800
• *Pizzeria* - Price: $500,000, Mortgage: $450,000, Cashflow: $2,500

*Expenses:*
*Taxes:* $360
*Mortgage/Rent Pay:* $300
*Car Loan:* $60
*Credit Card:* $60
*Small Credit:* $50
*Other Payments:* $450", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("I can sell businesses")]
        public void ICanSellBusinesses()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("I can sell businesses", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 44
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 45
 testRunner.Given("I am \'Timothy Fry\' user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 46
  testRunner.And("I play as \'Car mechanic\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 47
  testRunner.And("I get $200,000 in cash", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Title",
                            "Price",
                            "First Payment",
                            "Monthly Cashflow"});
                table2.AddRow(new string[] {
                            "Car wash",
                            "20,000",
                            "20,000",
                            "800"});
                table2.AddRow(new string[] {
                            "Company",
                            "25,000",
                            "20,000",
                            "1000"});
                table2.AddRow(new string[] {
                            "Enterprise",
                            "30,000",
                            "25,000",
                            "1500"});
                table2.AddRow(new string[] {
                            "Limited partnership",
                            "100,000",
                            "30,000",
                            "1600"});
                table2.AddRow(new string[] {
                            "Passage",
                            "150,000",
                            "40,000",
                            "1,800"});
                table2.AddRow(new string[] {
                            "Pizzeria",
                            "500,000",
                            "50,000",
                            "2500"});
#line 48
 testRunner.When("I buy businesses:", ((string)(null)), table2, "When ");
#line hidden
#line 56
  testRunner.But("I sell Car wash for $100,000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "But ");
#line hidden
#line 57
  testRunner.And("I sell Passage for $200,000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 58
 testRunner.Then("My Data is following:", @"*Profession:* Car mechanic
*Cash:* $206,390
*Salary:* $2,000
*Income:* $6,600
*Expenses:* $1,280
*Cashflow:* $7,320

*Assets:*
• *Company* - Price: $25,000, Mortgage: $5,000, Cashflow: $1,000
• *Enterprise* - Price: $30,000, Mortgage: $5,000, Cashflow: $1,500
• *Limited Partnership* - Price: $100,000, Mortgage: $70,000, Cashflow: $1,600
• *Pizzeria* - Price: $500,000, Mortgage: $450,000, Cashflow: $2,500

*Expenses:*
*Taxes:* $360
*Mortgage/Rent Pay:* $300
*Car Loan:* $60
*Credit Card:* $60
*Small Credit:* $50
*Other Payments:* $450", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 81
 testRunner.And("My history data is following:", @"• Get $200,000
• Buy Business. *Car Wash* - Price: $20,000, Cashflow: $800
• Buy Business. *Company* - Price: $25,000, Mortgage: $5,000, Cashflow: $1,000
• Buy Business. *Enterprise* - Price: $30,000, Mortgage: $5,000, Cashflow: $1,500
• Buy Business. *Limited Partnership* - Price: $100,000, Mortgage: $70,000, Cashflow: $1,600
• Buy Business. *Passage* - Price: $150,000, Mortgage: $110,000, Cashflow: $1,800
• Buy Business. *Pizzeria* - Price: $500,000, Mortgage: $450,000, Cashflow: $2,500
• Sell Business. *Car Wash* - Price: $100,000
• Sell Business. *Passage* - Price: $200,000", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("I can rollback buy action")]
        public void ICanRollbackBuyAction()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("I can rollback buy action", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 94
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 95
 testRunner.Given("I am \'Gabriela Johns\' user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 96
  testRunner.And("I play as \'Car mechanic\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 97
  testRunner.And("I get $50,000 in cash", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Title",
                            "Price",
                            "First Payment",
                            "Monthly Cashflow"});
                table3.AddRow(new string[] {
                            "Car wash",
                            "20,000",
                            "20,000",
                            "800"});
                table3.AddRow(new string[] {
                            "Company",
                            "25,000",
                            "20,000",
                            "1000"});
#line 98
 testRunner.When("I buy businesses:", ((string)(null)), table3, "When ");
#line hidden
#line 102
 testRunner.But("I rollback last action", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "But ");
#line hidden
#line 103
 testRunner.Then("I have $31,390 in cash", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 104
  testRunner.And("My passive income is $800", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 105
  testRunner.And("My assets are:", "• *Car Wash* - Price: $20,000, Cashflow: $800", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("I can rollback sell action")]
        public void ICanRollbackSellAction()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("I can rollback sell action", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 110
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 111
 testRunner.Given("I am \'Sidney Nielsen\' user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 112
  testRunner.And("I play as \'Car mechanic\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 113
  testRunner.And("I get $50,000 in cash", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Title",
                            "Price",
                            "First Payment",
                            "Monthly Cashflow"});
                table4.AddRow(new string[] {
                            "Car wash",
                            "20,000",
                            "20,000",
                            "800"});
                table4.AddRow(new string[] {
                            "Company",
                            "25,000",
                            "20,000",
                            "1000"});
#line 114
  testRunner.And("I buy businesses:", ((string)(null)), table4, "And ");
#line hidden
#line 118
 testRunner.When("I sell Car wash for $30,000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 119
 testRunner.But("I rollback last action", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "But ");
#line hidden
#line 120
 testRunner.Then("I have $11,390 in cash", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 121
  testRunner.And("My passive income is $1,800", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 122
  testRunner.And("My assets are:", "• *Car Wash* - Price: $20,000, Cashflow: $800\r\n• *Company* - Price: $25,000, Mort" +
                        "gage: $5,000, Cashflow: $1,000", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
