// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CashFlowBotTests.Tests.SmallCircle
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("GiveMoney")]
    [NUnit.Framework.CategoryAttribute("non-parallel")]
    [NUnit.Framework.CategoryAttribute("do-cleanup")]
    public partial class GiveMoneyFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "non-parallel",
                "do-cleanup"};
        
#line 1 "GiveMoney.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Tests/SmallCircle", "GiveMoney", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Profession"});
            table7.AddRow(new string[] {
                        "Haroon Stephens",
                        "Doctor"});
            table7.AddRow(new string[] {
                        "Ela Lynch",
                        "Pilot"});
            table7.AddRow(new string[] {
                        "Brodie Newton",
                        "Lawyer"});
            table7.AddRow(new string[] {
                        "Kaitlin Alvarez",
                        "Teacher"});
#line 7
 testRunner.Given("Few players:", ((string)(null)), table7, "Given ");
#line hidden
#line 14
 testRunner.When("Ela Lynch get $1000 as a credit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 15
  testRunner.And("Haroon Stephens get $5,000 in cash", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 16
  testRunner.And("Brodie Newton get $1,000 in cash", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 17
  testRunner.And("Kaitlin Alvarez get $2,000 in cash", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 18
  testRunner.And("Kaitlin Alvarez get $3,000 in cash", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 19
  testRunner.And("Kaitlin Alvarez get $5,000 in cash", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Opportunity",
                        "Title",
                        "Price",
                        "First Payment",
                        "Monthly Cashflow"});
            table8.AddRow(new string[] {
                        "Small",
                        "2/1",
                        "60,000",
                        "2,000",
                        "1,000"});
            table8.AddRow(new string[] {
                        "Big",
                        "8-plex",
                        "150,000",
                        "5,000",
                        "1,500"});
#line 20
  testRunner.And("Kaitlin Alvarez buys real estate:", ((string)(null)), table8, "And ");
#line hidden
#line 24
  testRunner.And("Kaitlin Alvarez goes to the Big Circle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can give money to friend on Small Circle")]
        public void CanGiveMoneyToFriendOnSmallCircle()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can give money to friend on Small Circle", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 26
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
#line 27
 testRunner.When("Haroon Stephens says \'Give money\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 28
 testRunner.Then("Haroon Stephens sees buttons: Ela Lynch, Brodie Newton, Bank, Cancel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can give money to friend")]
        public void CanGiveMoneyToFriend()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can give money to friend", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 30
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
#line 31
 testRunner.When("Haroon Stephens pays $1000 to Ela Lynch", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 32
 testRunner.Then("All users recieve notification:", "Haroon Stephens transferred $1,000 to Ela Lynch.", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Balance"});
                table9.AddRow(new string[] {
                            "Haroon Stephens",
                            "$7,950"});
                table9.AddRow(new string[] {
                            "Ela Lynch",
                            "$5,000"});
                table9.AddRow(new string[] {
                            "Brodie Newton",
                            "$3,480"});
                table9.AddRow(new string[] {
                            "Kaitlin Alvarez",
                            "$254,510"});
#line 36
 testRunner.And("Balance by users is:", ((string)(null)), table9, "And ");
#line hidden
#line 42
 testRunner.And("Haroon Stephens history data is following:", "• Get $5,000\r\n• Pay $1,000", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 47
 testRunner.And("Ela Lynch history data is following:", "• Get credit: $1,000\r\n• Get $1,000", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can rollback payment to a friend")]
        public void CanRollbackPaymentToAFriend()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can rollback payment to a friend", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 53
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
#line 54
 testRunner.When("Haroon Stephens pays $1000 to Ela Lynch", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 55
  testRunner.But("Haroon Stephens rollbacks last action", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "But ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Balance"});
                table10.AddRow(new string[] {
                            "Haroon Stephens",
                            "$8,950"});
                table10.AddRow(new string[] {
                            "Ela Lynch",
                            "$5,000"});
                table10.AddRow(new string[] {
                            "Brodie Newton",
                            "$3,480"});
                table10.AddRow(new string[] {
                            "Kaitlin Alvarez",
                            "$254,510"});
#line 56
 testRunner.Then("Balance by users is:", ((string)(null)), table10, "Then ");
#line hidden
#line 62
 testRunner.And("Haroon Stephens history data is following:", "• Get $5,000", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 66
 testRunner.And("Ela Lynch history data is following:", "• Get credit: $1,000\r\n• Get $1,000", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can rollback payment from a friend")]
        public void CanRollbackPaymentFromAFriend()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can rollback payment from a friend", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 72
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
#line 73
 testRunner.When("Haroon Stephens pays $1000 to Ela Lynch", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 74
  testRunner.But("Ela Lynch rollbacks last action", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "But ");
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Balance"});
                table11.AddRow(new string[] {
                            "Haroon Stephens",
                            "$7,950"});
                table11.AddRow(new string[] {
                            "Ela Lynch",
                            "$4,000"});
                table11.AddRow(new string[] {
                            "Brodie Newton",
                            "$3,480"});
                table11.AddRow(new string[] {
                            "Kaitlin Alvarez",
                            "$254,510"});
#line 75
 testRunner.Then("Balance by users is:", ((string)(null)), table11, "Then ");
#line hidden
#line 81
 testRunner.And("Haroon Stephens history data is following:", "• Get $5,000\r\n• Pay $1,000", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 86
 testRunner.And("Ela Lynch history data is following:", "• Get credit: $1,000", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can pay money to bank")]
        public void CanPayMoneyToBank()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can pay money to bank", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 91
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
#line 92
 testRunner.When("Haroon Stephens pays $1000 to bank", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 93
 testRunner.Then("All users recieve notification:", "Haroon Stephens transferred $1,000 to Bank.", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Balance"});
                table12.AddRow(new string[] {
                            "Haroon Stephens",
                            "$7,950"});
                table12.AddRow(new string[] {
                            "Ela Lynch",
                            "$4,000"});
                table12.AddRow(new string[] {
                            "Brodie Newton",
                            "$3,480"});
                table12.AddRow(new string[] {
                            "Kaitlin Alvarez",
                            "$254,510"});
#line 97
 testRunner.And("Balance by users is:", ((string)(null)), table12, "And ");
#line hidden
#line 103
 testRunner.And("Haroon Stephens history data is following:", "• Get $5,000\r\n• Pay $1,000", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can rollback payment to a bank")]
        public void CanRollbackPaymentToABank()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can rollback payment to a bank", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 109
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
#line 110
 testRunner.When("Haroon Stephens pays $1000 to bank", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 111
  testRunner.But("Haroon Stephens rollbacks last action", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "But ");
#line hidden
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Balance"});
                table13.AddRow(new string[] {
                            "Haroon Stephens",
                            "$8,950"});
                table13.AddRow(new string[] {
                            "Ela Lynch",
                            "$4,000"});
                table13.AddRow(new string[] {
                            "Brodie Newton",
                            "$3,480"});
                table13.AddRow(new string[] {
                            "Kaitlin Alvarez",
                            "$254,510"});
#line 112
 testRunner.Then("Balance by users is:", ((string)(null)), table13, "Then ");
#line hidden
#line 118
 testRunner.And("Haroon Stephens history data is following:", "• Get $5,000", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
