// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CashFlowBotTests.Tests.SmallCircle
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("RealEstate")]
    public partial class RealEstateFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "RealEstate.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Tests/SmallCircle", "RealEstate", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("I can buy real estate")]
        public void ICanBuyRealEstate()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("I can buy real estate", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 3
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
 testRunner.Given("I am \'Dewi Walls\' user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 5
  testRunner.And("I play as \'Pilot\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 6
  testRunner.And("I get $100,000 in cash", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Opportunity",
                            "Title",
                            "Price",
                            "First Payment",
                            "Monthly Cashflow"});
                table5.AddRow(new string[] {
                            "Small",
                            "2/1",
                            "60,000",
                            "2,000",
                            "160"});
                table5.AddRow(new string[] {
                            "Small",
                            "3/2",
                            "65,000",
                            "3,000",
                            "-100"});
                table5.AddRow(new string[] {
                            "Big",
                            "3/2",
                            "90,000",
                            "7,000",
                            "400"});
                table5.AddRow(new string[] {
                            "Big",
                            "2-plex",
                            "125,000",
                            "9,000",
                            "500"});
                table5.AddRow(new string[] {
                            "Big",
                            "8-plex",
                            "150,000",
                            "10,000",
                            "1,600"});
#line 7
 testRunner.When("I buy real estate:", ((string)(null)), table5, "When ");
#line hidden
#line 14
 testRunner.Then("My Data is following:", @"*Profession:* Pilot
*Cash:* $72,000
*Salary:* $9,500
*Income:* $2,560
*Expenses:* $6,900
*Cash Flow*: $5,160

*Assets:*
• *2/1* - Price: $60,000, Mortgage: $58,000, Cash Flow: $160
• *3/2* - Price: $65,000, Mortgage: $62,000, Cash Flow: -$100
• *3/2* - Price: $90,000, Mortgage: $83,000, Cash Flow: $400
• *2-plex* - Price: $125,000, Mortgage: $116,000, Cash Flow: $500
• *8-plex* - Price: $150,000, Mortgage: $140,000, Cash Flow: $1,600

*Expenses:*
*Taxes:* $2,350
*Mortgage/Rent Pay:* $1,330
*Car Loan:* $300
*Credit Card:* $660
*Small Credit:* $50
*Other Payments:* $2,210", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("I can sell real estate")]
        public void ICanSellRealEstate()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("I can sell real estate", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 39
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 40
 testRunner.Given("I am \'Jacques Hamilton\' user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 41
  testRunner.And("I play as \'Pilot\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 42
  testRunner.And("I get $100,000 in cash", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Opportunity",
                            "Title",
                            "Price",
                            "First Payment",
                            "Monthly Cashflow"});
                table6.AddRow(new string[] {
                            "Small",
                            "2/1",
                            "60,000",
                            "2,000",
                            "160"});
                table6.AddRow(new string[] {
                            "Small",
                            "3/2",
                            "65,000",
                            "3,000",
                            "-100"});
                table6.AddRow(new string[] {
                            "Big",
                            "3/2",
                            "90,000",
                            "7,000",
                            "400"});
                table6.AddRow(new string[] {
                            "Big",
                            "2-plex",
                            "125,000",
                            "9,000",
                            "500"});
                table6.AddRow(new string[] {
                            "Big",
                            "8-plex",
                            "150,000",
                            "10,000",
                            "1,600"});
#line 43
 testRunner.When("I buy real estate:", ((string)(null)), table6, "When ");
#line hidden
#line 50
  testRunner.But("I sell 2/1 for $100,000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "But ");
#line hidden
#line 51
  testRunner.And("I sell 8-plex for $45,000 each", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 52
 testRunner.Then("My Data is following:", @"*Profession:* Pilot
*Cash:* $334,000
*Salary:* $9,500
*Income:* $800
*Expenses:* $6,900
*Cash Flow*: $3,400

*Assets:*
• *3/2* - Price: $65,000, Mortgage: $62,000, Cash Flow: -$100
• *3/2* - Price: $90,000, Mortgage: $83,000, Cash Flow: $400
• *2-plex* - Price: $125,000, Mortgage: $116,000, Cash Flow: $500

*Expenses:*
*Taxes:* $2,350
*Mortgage/Rent Pay:* $1,330
*Car Loan:* $300
*Credit Card:* $660
*Small Credit:* $50
*Other Payments:* $2,210", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 74
 testRunner.And("My history data is following:", @"• Get $100,000
• Buy Real Estate. *2/1* - Price: $60,000, Mortgage: $58,000, Cash Flow: $160
• Buy Real Estate. *3/2* - Price: $65,000, Mortgage: $62,000, Cash Flow: -$100
• Buy Real Estate. *3/2* - Price: $90,000, Mortgage: $83,000, Cash Flow: $400
• Buy Real Estate. *2-plex* - Price: $125,000, Mortgage: $116,000, Cash Flow: $500
• Buy Real Estate. *8-plex* - Price: $150,000, Mortgage: $140,000, Cash Flow: $1,600
• Sell Real Estate. *2/1* - Price: $100,000
• Sell Real Estate. *8-plex* - Price: $45,000", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("I can rollback buy transaction")]
        public void ICanRollbackBuyTransaction()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("I can rollback buy transaction", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 86
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 87
 testRunner.Given("I am \'Lilli Atkins\' user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 88
  testRunner.And("I play as \'Pilot\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 89
  testRunner.And("I get $10,000 in cash", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Opportunity",
                            "Title",
                            "Price",
                            "First Payment",
                            "Monthly Cashflow"});
                table7.AddRow(new string[] {
                            "Small",
                            "2/1",
                            "60,000",
                            "2,000",
                            "160"});
                table7.AddRow(new string[] {
                            "Big",
                            "8-plex",
                            "150,000",
                            "10,000",
                            "1,600"});
#line 90
 testRunner.When("I buy real estate:", ((string)(null)), table7, "When ");
#line hidden
#line 94
  testRunner.But("I rollback last action", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "But ");
#line hidden
#line 95
 testRunner.Then("I have $11,000 in cash", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 96
  testRunner.And("My passive income is $160", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 97
  testRunner.And("My assets are:", "• *2/1* - Price: $60,000, Mortgage: $58,000, Cash Flow: $160", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("I can rollback sell transaction")]
        public void ICanRollbackSellTransaction()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("I can rollback sell transaction", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 102
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 103
 testRunner.Given("I am \'Zaina Ramirez\' user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 104
  testRunner.And("I play as \'Pilot\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 105
  testRunner.And("I get $10,000 in cash", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Opportunity",
                            "Title",
                            "Price",
                            "First Payment",
                            "Monthly Cashflow"});
                table8.AddRow(new string[] {
                            "Small",
                            "2/1",
                            "60,000",
                            "2,000",
                            "160"});
                table8.AddRow(new string[] {
                            "Big",
                            "8-plex",
                            "150,000",
                            "10,000",
                            "1,600"});
#line 106
 testRunner.When("I buy real estate:", ((string)(null)), table8, "When ");
#line hidden
#line 110
  testRunner.And("I sell 2/1 for $100,000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 111
  testRunner.But("I rollback last action", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "But ");
#line hidden
#line 112
 testRunner.Then("I have $1,000 in cash", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 113
  testRunner.And("My passive income is $1,760", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 114
  testRunner.And("My assets are:", "• *2/1* - Price: $60,000, Mortgage: $58,000, Cash Flow: $160\r\n• *8-plex* - Price:" +
                        " $150,000, Mortgage: $140,000, Cash Flow: $1,600", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
