//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashFlowBot.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Terms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Terms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CashFlowBot.Data.Terms", typeof(Terms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture RealEstate for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Terms (ID, Language, Term) VALUES
        ///(0, &apos;EN&apos;, &apos;Your Cash Flow is *{0}*. How much should you get?&apos;),
        ///(1, &apos;EN&apos;, &apos;How much would you give?&apos;),
        ///(2, &apos;EN&apos;, &apos;Hey {0}, your have {1} children. Get one more?&apos;),
        ///(3, &apos;EN&apos;, &apos;Are you sure want to stop current game?&apos;),
        ///(4, &apos;EN&apos;, &apos;Yes&apos;),
        ///(5, &apos;EN&apos;, &apos;You don&apos;&apos;t have enough money.&apos;),
        ///(6, &apos;EN&apos;, &apos;Cancel&apos;),
        ///(7, &apos;EN&apos;, &apos;Title:&apos;),
        ///(8, &apos;EN&apos;, &apos;What is the price?&apos;),
        ///(9, &apos;EN&apos;, &apos;Invalid price value. Try again.&apos;),
        ///(10, &apos;EN&apos;, &apos;What is the first payment?&apos;),
        ///(11, &apos;EN&apos;,  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string terms_en {
            get {
                return ResourceManager.GetString("terms_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Terms (ID, Language, Term) VALUES
        ///(0, &apos;UA&apos;, &apos;Ваш грошовий потік *{0}*. Скільки грошей отримати?&apos;),
        ///(1, &apos;UA&apos;, &apos;Скільки грошей дати?&apos;),
        ///(2, &apos;UA&apos;, &apos;{0}, у вас {1} дітей. Хочете ще?&apos;),
        ///(3, &apos;UA&apos;, &apos;Точно бажаєте закінчити поточну гру?&apos;),
        ///(4, &apos;UA&apos;, &apos;Так&apos;),
        ///(5, &apos;UA&apos;, &apos;У вас не вистачає грошей.&apos;),
        ///(6, &apos;UA&apos;, &apos;Скасувати&apos;),
        ///(7, &apos;UA&apos;, &apos;Назва:&apos;),
        ///(8, &apos;UA&apos;, &apos;Яка ціна?&apos;),
        ///(9, &apos;UA&apos;, &apos;Некоректне значення ціни. Спробуй ще раз.&apos;),
        ///(10, &apos;UA&apos;, &apos;Який перший платіж?&apos;),
        ///(11, &apos;UA&apos;, &apos;Некоректне зачення першого [rest of string was truncated]&quot;;.
        /// </summary>
        public static string terms_ua {
            get {
                return ResourceManager.GetString("terms_ua", resourceCulture);
            }
        }
    }
}
