//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashFlowBot.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Terms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Terms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CashFlowBot.Data.Terms", typeof(Terms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Terms (ID, Language, Term) VALUES
        ///(0, &apos;DE&apos;, &apos;Ihr Cash-Flow ist *{0}*. Wie viel sollten Sie bekommen?&apos;),
        ///(1, &apos;DE&apos;, &apos;Eintreten den Großen Kreis&apos;),
        ///(2, &apos;DE&apos;, &apos;Transaktionen&apos;),
        ///(3, &apos;DE&apos;, &apos;Wollen Sie das Spiel beenden?&apos;),
        ///(4, &apos;DE&apos;, &apos;Ja&apos;),
        ///(5, &apos;DE&apos;, &apos;Sie haben nicht genug Geld.&apos;),
        ///(6, &apos;DE&apos;, &apos;Absagen&apos;),
        ///(7, &apos;DE&apos;, &apos;Titel:&apos;),
        ///(8, &apos;DE&apos;, &apos;Was is der Wert?&apos;),
        ///(9, &apos;DE&apos;, &apos;Falsh Wert. Versuchen Sie es nochmal.&apos;),
        ///(10, &apos;DE&apos;, &apos;Was ist der erste Betrag?&apos;),
        ///(11, &apos;DE&apos;, &apos;Falsh erster Betrag.&apos;),
        ///(12, &apos;DE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string terms_de {
            get {
                return ResourceManager.GetString("terms_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Terms (ID, Language, Term) VALUES
        ///(0, &apos;EN&apos;, &apos;Your Cash Flow is *{0}*. How many should you get?&apos;),
        ///(1, &apos;EN&apos;, &apos;Go to Big Circle&apos;),
        ///(2, &apos;EN&apos;, &apos;History&apos;),
        ///(3, &apos;EN&apos;, &apos;Are you sure want to stop current game?&apos;),
        ///(4, &apos;EN&apos;, &apos;Yes&apos;),
        ///(5, &apos;EN&apos;, &apos;You don&apos;&apos;t have enough money.&apos;),
        ///(6, &apos;EN&apos;, &apos;Cancel&apos;),
        ///(7, &apos;EN&apos;, &apos;Title:&apos;),
        ///(8, &apos;EN&apos;, &apos;What is the price?&apos;),
        ///(9, &apos;EN&apos;, &apos;Invalid price value. Try again.&apos;),
        ///(10, &apos;EN&apos;, &apos;What is the first payment?&apos;),
        ///(11, &apos;EN&apos;, &apos;Invalid first payment amount.&apos;),
        ///(12, &apos;EN&apos;, &apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string terms_en {
            get {
                return ResourceManager.GetString("terms_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Terms (ID, Language, Term) VALUES
        ///(0, &apos;UA&apos;, &apos;Ваш грошовий потік *{0}*. Скільки грошей отримати?&apos;),
        ///(1, &apos;UA&apos;, &apos;Перейти до Великого Кола&apos;),
        ///(2, &apos;UA&apos;, &apos;Історія&apos;),
        ///(3, &apos;UA&apos;, &apos;Точно бажаєте закінчити поточну гру?&apos;),
        ///(4, &apos;UA&apos;, &apos;Так&apos;),
        ///(5, &apos;UA&apos;, &apos;У вас не вистачає грошей.&apos;),
        ///(6, &apos;UA&apos;, &apos;Скасувати&apos;),
        ///(7, &apos;UA&apos;, &apos;Назва:&apos;),
        ///(8, &apos;UA&apos;, &apos;Яка ціна?&apos;),
        ///(9, &apos;UA&apos;, &apos;Некоректне значення ціни. Спробуй ще раз.&apos;),
        ///(10, &apos;UA&apos;, &apos;Який перший платіж?&apos;),
        ///(11, &apos;UA&apos;, &apos;Некоректне зачення першого платежа.&apos;),
        ///(12, &apos;U [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string terms_ua {
            get {
                return ResourceManager.GetString("terms_ua", resourceCulture);
            }
        }
    }
}
