INSERT INTO Terms (ID, Language, Term) VALUES
(0, 'EN', 'Your Cash Flow is *{0}*. How many should you get?'),
(1, 'EN', 'Go to Big Circle'),
(2, 'EN', 'History'),
(3, 'EN', 'Are you sure want to stop current game?'),
(4, 'EN', 'Yes'),
(5, 'EN', 'You don''t have enough money.'),
(6, 'EN', 'Cancel'),
(7, 'EN', 'Title:'),
(8, 'EN', 'What is the price?'),
(9, 'EN', 'Invalid price value. Try again.'),
(10, 'EN', 'What is the first payment?'),
(11, 'EN', 'Invalid first payment amount.'),
(12, 'EN', 'What is the cash flow?'),
(13, 'EN', 'Done.'),
(14, 'EN', 'What Real Estate do you want to sell?{0}{1}'),
(15, 'EN', 'You have no Real Estates.'),
(16, 'EN', 'Invalid Real Estate number.'),
(17, 'EN', 'You can buy up to {0} stocks. How many stocks would you like to buy?'),
(18, 'EN', 'Invalid quantity value. Try again.'),
(19, 'EN', '{0} x {1} = {2}. You have only {3}. You can buy *{4}* stocks. So, what quantity of stocks do you want to buy?'),
(20, 'EN', '{0}, you have *{1}* children expenses and {2} child.'),
(21, 'EN', 'How many?'),
(22, 'EN', 'Ok, you''ve got *{0}*'),
(23, 'EN', 'You don''t have *{0}*, but only *{1}*'),
(24, 'EN', 'Invalid amount. The amount must be a multiple of 1000'),
(25, 'EN', '{0}, you have *{1}* children expenses and {2} children.'),
(26, 'EN', 'Please stop the current game before starting a new one.'),
(27, 'EN', 'What stocks do you want to sell?'),
(28, 'EN', 'Choose your *profession*'),
(29, 'EN', 'Profession not found. Try again.'),
(30, 'EN', 'Welcome, {0}!'),
(31, 'EN', 'Show my Data'),
(32, 'EN', 'Get Money'),
(33, 'EN', 'Give Money'),
(34, 'EN', 'Get Credit'),
(35, 'EN', 'Buy Stocks'),
(36, 'EN', 'Sell Stocks'),
(37, 'EN', 'Buy Real Estate'),
(38, 'EN', 'Sell Real Estate'),
(39, 'EN', 'Baby'),
(40, 'EN', 'Reduce Liabilities'),
(41, 'EN', 'Stop Game'),
(42, 'EN', 'monthly'),
(43, 'EN', 'Mortgage'),
(44, 'EN', 'School Loan'),
(45, 'EN', 'Car Loan'),
(46, 'EN', 'Credit Card'),
(47, 'EN', 'Bank Loan'),
(48, 'EN', 'You don''t have money to reduce liabilities, your balance is {0}'),
(49, 'EN', 'You have no stocks.'),
(50, 'EN', 'Profession'),
(51, 'EN', 'Cash'),
(52, 'EN', 'Salary'),
(53, 'EN', 'Income'),
(54, 'EN', 'Expenses'),
(55, 'EN', 'Cash Flow'),
(56, 'EN', 'Assets'),
(57, 'EN', 'You''re lucky parent of three children. You don''t need one more.'),
(58, 'EN', 'Taxes'),
(59, 'EN', 'Mortgage/Rent Pay'),
(60, 'EN', 'Other Payments'),
(61, 'EN', 'Children'),
(62, 'EN', 'Children Expenses'),
(63, 'EN', 'per child'),
(64, 'EN', 'Price'),
(65, 'EN', 'Initial'),
(66, 'EN', 'Current'),
(67, 'EN', 'Target'),
(68, 'EN', 'Your income is greater, then expenses. You are ready for Big Circle.'),
(69, 'EN', 'Divorce'),
(70, 'EN', 'Tax Audit'),
(71, 'EN', 'Lawsuit'),
(72, 'EN', 'You''ve lost {0}.'),
(73, 'EN', 'You are the winner!'),
(74, 'EN', 'Buy Business'),
(75, 'EN', 'Sell Business'),
(76, 'EN', 'Invalid Business number.'),
(77, 'EN', 'You have no Business.'),
(78, 'EN', 'What Business do you want to sell?{0}{1}.'),
(79, 'EN', 'Pay Check'),
(80, 'EN', 'Downsize'),
(81, 'EN', 'Small Opportunity'),
(82, 'EN', 'Stocks 2 to 1'),
(83, 'EN', 'Stocks 1 to 2'),
(84, 'EN', 'Big Opportunity'),
(85, 'EN', 'Market'),
(86, 'EN', 'Doodads'),
(87, 'EN', 'You were fired. You''ve payed total amount of your expenses: *{0}* and lose 2 turns.'),
(88, 'EN', 'You''ve taken *{0}* from bank.'),
(89, 'EN', 'What do you want?'),
(90, 'EN', 'Charity - Pay 10%'),
(91, 'EN', 'You''ve payed {0}, now you can use two dice in next 3 turns.'),
(92, 'EN', 'Small Credit'),
(93, 'EN', 'You have no liabilities.'),
(94, 'EN', 'Buy Land'),
(95, 'EN', 'Pay with Cash'),
(96, 'EN', 'Pay with Credit Card'),
(97, 'EN', 'What is the monthly payment?'),
(98, 'EN', 'Sell Land'),
(99, 'EN', 'What Land do you want to sell?{0}{1}'),
(100, 'EN', 'You have no Land.'),
(101, 'EN', 'Invalid land number.'),
(102, 'EN', 'Main menu'),
(103, 'EN', 'Pay {0}'),
(104, 'EN', 'Get {0}'),
(105, 'EN', 'Get a child'),
(106, 'EN', 'Downsize and paying {0}'),
(107, 'EN', 'Get credit: {0}'),
(108, 'EN', 'Charity: {0}'),
(109, 'EN', 'Rollback last action'),
(110, 'EN', 'Are you sure want to rollback last action?'),
(111, 'EN', 'No records found.'),
(112, 'EN', 'Buy a boat'),
(113, 'EN', 'You already have a boat.'),
(114, 'EN', 'Boat Loan'),
--(115, 'EN', 'Pay off a boat loan. '),
(116, 'EN', 'Boat'),
(117, 'EN', 'You''ve bought a boat for {0} in credit, first payment is {1}, monthly payment is {2}'),

(1001, 'EN', 'Lawyer'),
(1002, 'EN', 'Business manager'),
(1003, 'EN', 'Engineer'),
(1004, 'EN', 'Track driver'),
(1005, 'EN', 'Janitor'),
(1006, 'EN', 'Nurse'),
(1007, 'EN', 'Police officer'),
(1008, 'EN', 'Doctor'),
(1009, 'EN', 'Teacher'),
(1010, 'EN', 'Car mechanic'),
(1011, 'EN', 'Secretary'),
(1012, 'EN', 'Pilot')
