INSERT INTO Terms (ID, Language, Term) VALUES
(0, 'DE', 'Ihr Cash-Flow ist *{0}*. Wie viel sollten Sie bekommen?'),
(1, 'DE', 'Eintreten den Großen Kreis'),
(2, 'DE', 'Transaktionen'),
(3, 'DE', 'Wollen Sie das Spiel beenden?'),
(4, 'DE', 'Ja'),
(5, 'DE', 'Sie haben nicht genug Geld.'),
(6, 'DE', 'Absagen'),
(7, 'DE', 'Titel:'),
(8, 'DE', 'Was is der Wert?'),
(9, 'DE', 'Falsh Wert. Versuchen Sie es nochmal.'),
(10, 'DE', 'Was ist der erste Betrag?'),
(11, 'DE', 'Falsh erster Betrag.'),
(12, 'DE', 'Was ist der Cash-Flow?'),
(13, 'DE', 'Gemacht.'),
(14, 'DE', 'Welche Immobilien wollen Sie verkaufen?{0}{1}'),
(15, 'DE', 'Sie haben keine Immobilien.'),
(16, 'DE', 'Falsh Immobiliennummer.'),
(17, 'DE', 'Sie können bis zu {0} Aktien kaufen. Wie viele Aktien möchten Sie kaufen?'),
(18, 'DE', 'Ungültige Aktienmenge. Versuchen Sie es nochmal.'),
(19, 'DE', '{0} x {1} = {2}. Sie haben nur {3}. Sie können *{4}* Aktien kaufen. Also, welche Menge an Aktien möchten Sie kaufen?'),
(20, 'DE', '{0}, Sie haben *{1}* Kindernausgaben und {2} Kind.'),
(21, 'DE', 'Wie fiel?'),
(22, 'DE', 'Okay, Sie bekommen *{0}*'),
(23, 'DE', 'Sie haben nicht *{0}*, sondern nur *{1}*'),
(24, 'DE', 'Ungültige Menge. Der Betrag muss ein Vielfaches von 1000 sein.'),
(25, 'DE', '{0}, Sie haben *{1}* Kindernausgaben und {2} Kindern.'),
(26, 'DE', 'Bitte stoppen Sie das aktuelle Spiel, bevor Sie ein neues starten.'),
(27, 'DE', 'Welche Aktien möchten Sie verkaufen?'),
(28, 'DE', 'Was ist dein Beruf?'),
(29, 'DE', 'Falsh Beruf. Versuchen Sie es nochmal.'),
(30, 'DE', 'Wilkommen, {0}!'),
(31, 'DE', 'Meine Info'),
(32, 'DE', 'Geld bekomen'),
(33, 'DE', 'Geld geben'),
(34, 'DE', 'Kredit bekomen'),
(35, 'DE', 'Aktien kaufen'),
(36, 'DE', 'Aktien verkaufen'),
(37, 'DE', 'Immobilien kaufen'),
(38, 'DE', 'Immobilien verkaufen'),
(39, 'DE', 'Kind'),
(40, 'DE', 'Verbindlichkeiten reduzieren'),
(41, 'DE', 'Spiel beenden'),
(42, 'DE', 'monatlich'),
(43, 'DE', 'Hypothek'),
(44, 'DE', 'Schuldarlehen'),
(45, 'DE', 'Autokredit'),
(46, 'DE', 'Kreditkarte'),
(47, 'DE', 'Bankkredit'),
(48, 'DE', 'Sie haben kein Geld, um Verbindlichkeiten zu reduzieren, Ihr Guthaben beträgt ist {0}'),
(49, 'DE', 'Sie haben keine Aktien.'),
(50, 'DE', 'Beruf'),
(51, 'DE', 'Bargeld'),
(52, 'DE', 'Gehalt'),
(53, 'DE', 'Einkommen'),
(54, 'DE', 'Ausgaben'),
(55, 'DE', 'Cash-Flow'),
(56, 'DE', 'Aktiva'),
(57, 'DE', 'Sie haben bereits drei Kinder. Sie brauchen keinen mehr.'),
(58, 'DE', 'Steuern'),
(59, 'DE', 'Hypotheken/Mietzinsen'),
(60, 'DE', 'Andere Zahlungen'),
(61, 'DE', 'Kindern'),
(62, 'DE', 'Kindernausgaben'),
(63, 'DE', 'pro Kind'),
(64, 'DE', 'der Wert'),
(65, 'DE', 'Initial'),
(66, 'DE', 'Anwesend'),
(67, 'DE', 'Ziel'),
(68, 'DE', 'Die Einkommen von {0} sind größer als Ausgaben. {0} ist bereit für den großen Kreis.'),
(69, 'DE', 'die Ehescheidung'),
(70, 'DE', 'die Steuerprüfung'),
(71, 'DE', 'die Klage'),
(72, 'DE', 'Sie haben *{0}* bezahlt.'),
(73, 'DE', 'Sie sind Sieger!'),
(74, 'DE', 'Geschäft kaufen'),
(75, 'DE', 'Geschäft verkaufen'),
(76, 'DE', 'False Geschäftnummer.'),
(77, 'DE', 'Sie haben kein Geschäft.'),
(78, 'DE', 'Welcher Geschäft wollen Sie verkaufen?{0}{1}.'),
(79, 'DE', 'Gehalt'),
(80, 'DE', 'Entlassung'),
(81, 'DE', 'Kleine Chance'),
(82, 'DE', 'Aktien x2'),
(83, 'DE', 'Aktien ÷2'),
(84, 'DE', 'Große Chance'),
(85, 'DE', 'Markt'),
(86, 'DE', 'Doodads'),
(87, 'DE', 'Sie sind entlassen. Sie haben den Gesamtbetrag Ihrer Ausgaben bezahlt: *{0}* und 2 Runden verliren.'),
(88, 'DE', 'Sie haben *{0}* aus der Bank genommen.'),
(89, 'DE', 'Was wollen Sie?'),
(90, 'DE', 'Nächstenliebe - 10% Zahlen'),
(91, 'DE', 'Sie haben {0} bezahlt. Jetzt können Sie in den nächsten 3 Runden zwei Würfel verwenden.'),
(92, 'DE', 'Klein Kredit'),
(93, 'DE', 'Sie haben keine Schuld.'),
(94, 'DE', 'Land kaufen'),
(95, 'DE', 'Mit Bargeld zahlen'),
(96, 'DE', 'Mit Kreditkarte zahlen'),
(97, 'DE', 'Wie ist die monatliche Zhahlung?'),
(98, 'DE', 'Land verkaufen'),
(99, 'DE', 'Welches Land wollen Sie verkaufen?{0}{1}'),
(100, 'DE', 'Sie haben kein Land.'),
(101, 'DE', 'Falsh Landnummer.'),
(102, 'DE', 'Hauptmenü'),
(103, 'DE', 'Bezahlen {0}'),
(104, 'DE', 'Kriegen {0}'),
(105, 'DE', 'Kind bekommen'),
(106, 'DE', 'Entlassung. Bezahlen {0}'),
(107, 'DE', 'Kredit bekommen: {0}'),
(108, 'DE', 'Nächstenliebe: {0}'),
(109, 'DE', 'Rollback der letzten Transaktion'),
(110, 'DE', 'Möchten Sie die letzte Transaktion wirklich rückgängig machen?'),
(111, 'DE', 'Nichts zu zeigen'),
(112, 'DE', 'Boot kaufen'),
(113, 'DE', 'Sie haben schon ein Boot.'),
(114, 'DE', 'Bootredit'),
(115, 'DE', 'Gründe eine Firma'),
(116, 'DE', 'Boot'),
(117, 'DE', 'Sie haben ein Boot für {0} gekauft, erste Zahlung ist {1}, monatliche Zahlung ist {2}'),
(118, 'DE', 'Cashflow erhöhen'),
(119, 'DE', 'Münzen kaufen'),
(120, 'DE', 'Münzen verkaufen'),
(121, 'DE', 'Sie haben keinen Münzen.'),
(122, 'DE', 'Welche Münzen möchten Sie verkaufen?'),
(123, 'DE', 'Falshen Münzentitel.'),
(124, 'DE', 'Münzen Aktiennamen.'),
(125, 'DE', 'Bankrott'),
(126, 'DE', 'Sie haben kein Geld.'),
(127, 'DE', 'Sie müssen Ihre Vermögenswerte verkaufen, bis Ihr Cashflow positiv ist.'),
(128, 'DE', 'Welchen Vermögenswert möchten Sie verkaufen?'),
(129, 'DE', 'Sie sind bankrott. Das Spiel ist vorbei.'),
(130, 'DE', 'Du hast deine Schulden abbezahlt, verlierst 3 Runden und kannst weitermachen.'),
(131, 'DE', 'Verkauf für Schulden'),
(132, 'DE', 'Umschuldung'),
(133, 'DE', 'Kreditrückzahlung in Höhe von *{0}*'),
(134, 'DE', 'Umschuldung. Autokredite, Kleinkredite und Kreditkarte halbiert.'),
(135, 'DE', 'Kreditrückzahlung'),
(136, 'DE', 'Sie haben kein Kleingewerbe.'),
(137, 'DE', 'Sie haben *{0}* Wohnungen. Was ist der Preis pro Wohnung?'),
(138, 'DE', 'Nein'),
(139, 'DE', 'Wähle zufällig'),
(140, 'DE', 'Freunde'),
(141, 'DE', 'There are no other players.'),
(142, 'DE', 'Auf kleinem Kreis:'),
(143, 'DE', 'Auf großem Kreis:'),
(144, 'DE', 'Überweisung'),
(145, 'DE', 'Nicht gefunden'),
(146, 'DE', '{0} überwies {2} an {1}.'),
(147, 'DE', 'Wem?'),
(148, 'DE', '{0} gewinnt das Spiel!'),

(1001, 'DE', 'Umwalt'),
(1002, 'DE', 'Manager'),
(1003, 'DE', 'Ingenieur'),
(1004, 'DE', 'Lkw Fahrer'),
(1005, 'DE', 'Hausmeister'),
(1006, 'DE', 'Krankenschwester'),
(1007, 'DE', 'Polizist'),
(1008, 'DE', 'Arzt'),
(1009, 'DE', 'Lehrer'),
(1010, 'DE', 'Automechaniker'),
(1011, 'DE', 'Sekretär'),
(1012, 'DE', 'Pilot')
