name: E2E Tests (Nix)

on:
  workflow_call:
    inputs:
      RUN_ON:
        required: true
        type: string

    secrets:
      BOT_TOKEN:
        required: true
      API_ID:
        required: true
      API_HASH:
        required: true
      PHONE_NUMBER:
        required: true
      TESTING_SESSION:
        required: true

jobs:
  tests:
    runs-on: ${{ inputs.RUN_ON }}

    env:
      CASHFLOW_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      API_ID: ${{ secrets.API_ID }}
      API_HASH: ${{ secrets.API_HASH }}
      PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET SDK 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore CashFlowBot.sln

      - name: Save secrets
        run: |
          echo "${{ secrets.BOT_TOKEN }}" > CashFlowBot/BotID.txt
          echo "${{ secrets.TESTING_SESSION }}" | base64 --decode > CashFlowBotE2eTests/testing_session.session

      - name: Build solution
        run: dotnet build CashFlowBot.sln --configuration Release --no-restore

      - name: Run E2E Tests
        run: |
          dotnet run --project CashFlowBot &
          BOT_PID=$!
          sleep 5
          dotnet test CashFlowBotE2eTests/CashFlowBotE2eTests.csproj --configuration Release --no-build
          kill $BOT_PID
