name: Build and Test (.NET 8)

on: pull_request

jobs:
  build:
    uses: ./.github/workflows/build.yml

  _1_tests:
    name: Test
    needs: build
    uses: ./.github/workflows/unit.yml

  _2_tests:
    if: ${{ !github.event.pull_request.draft }}
    name: Test
    needs: _1_tests
    uses: ./.github/workflows/system.yml

  _3_tests:
    if: ${{ !github.event.pull_request.draft }}
    name: Test
    needs: _2_tests
    uses: ./.github/workflows/e2e-win.yml
    secrets: inherit

  _4_tests:
    if: ${{ !github.event.pull_request.draft }}
    name: Test
    needs: _3_tests
    uses: ./.github/workflows/e2e-nix.yml
    with:
      OS: Linux
      RUN_ON: ubuntu-latest
    secrets: inherit

  _5_tests:
    if: ${{ !github.event.pull_request.draft }}
    name: Test
    needs: _4_tests
    uses: ./.github/workflows/e2e-nix.yml
    with:
      OS: MacOs
      RUN_ON: macos-latest
    secrets: inherit
