name: Build and Test (.NET 8)

on: pull_request

jobs:
  build:
    uses: ./.github/workflows/build.yml

  1_tests:
    name: Test
    needs: build
    uses: ./.github/workflows/unit.yml

  2_tests:
    if: ${{ !github.event.pull_request.draft }}
    name: Test
    needs: unit-tests
    uses: ./.github/workflows/system.yml

  3_tests:
    if: ${{ !github.event.pull_request.draft }}
    needs: system-tests
    uses: ./.github/workflows/e2e-win.yml
    secrets: inherit

  4_tests:
    if: ${{ !github.event.pull_request.draft }}
    name: Test
    needs: e2e-win
    uses: ./.github/workflows/e2e-nix.yml
    with:
      OS: Linux
      RUN_ON: ubuntu-latest
    secrets: inherit

  5_tests:
    if: ${{ !github.event.pull_request.draft }}
    name: Test
    needs: e2e-linux
    uses: ./.github/workflows/e2e-nix.yml
    with:
      OS: MacOs
      RUN_ON: macos-latest
    secrets: inherit
