name: System Test

on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET SDK 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - uses: actions/download-artifact@v4
        with:
          name: build
          path: ./

      - name: Run System Tests
        run: dotnet test CashFlowBotSystemTests/CashFlowBotSystemTests.csproj --configuration Release --no-build --verbosity quiet --logger "html;LogFileName=SystemTests.html"

      - name: Upload logs and messages
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: system-tests
          path: |
            CashFlowBotSystemTests/TestResults/
            emulator/
          retention-days: 7

