name: Build and Test (.NET 8)

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET SDK 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore CashFlowBot.sln

      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Build solution
        run: dotnet build CashFlowBot.sln --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test CashFlowUnitTests/CashFlowUnitTests.csproj --configuration Release --no-build --verbosity quiet --logger "trx;LogFileName=UnitTests.trx"

      - name: Generate Unit Tests report
        if: always()
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          reportgenerator -reports: "**/UnitTests.trx" -targetDir: "TestReports" -reporttypes:Html

      - name: Upload Unit Tests report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestReport
          path: TestReports/
          retention-days: 7

#      - name: Build Bot Emulator
#        run: dotnet publish CashFlowBotEmulator/CashFlowBotEmulator.csproj -c Release -o ./emulator -r linux-x64 --self-contained true
#
#      - name: Launch Bot Emulator
#        run: |
#          cd emulator
#          chmod +x CashFlowBotEmulator
#          ./CashFlowBotEmulator &
#
#      - name: Run System Tests
#        run: dotnet test CashFlowBotSystemTests/CashFlowBotSystemTests.csproj --configuration Release --no-build --verbosity quiet --consoleLoggerParameters:ErrorsOnly
#
#      - name: Upload logs and messages
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: logs-and-messages
#          path: |
#            emulator/Logs/*.*
#            emulator/*.msg
#            emulator/*.db
#          retention-days: 7